/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-104467-gf6ab103bb5-20211105"
#endif /* AVUTIL_FFVERSION_H */
